# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: CD appforseii2526api

on:
  push:
    branches: 
        - CI-Pachoclos
   #     - development
    #paths:
     #   - 'src/AppForSEII2526.API**'
  workflow_dispatch:
  
  


jobs:
  build:

    runs-on: windows-latest
    permissions:
        contents: read

    env:
      API: ./src/AppForSEII2526.API/AppForSEII2526.API.csproj
      
      UT: ./test/AppForSEII2526.UT/AppForSEII2526.UT.csproj
     

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4


      - name: Set up .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: |
          dotnet restore ${{ env.API }}
          
          dotnet restore ${{ env.UT }}
          

      - name: Build the solution
        run: |
            dotnet build ${{ env.API }} --configuration Release --no-restore
           
            dotnet build ${{ env.UT }} --configuration Release --no-restore
            
        
      - name: Run unit tests with report
        run: dotnet test ${{ env.UT }} --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: TestResults
          path: ./test/AppForSEII2526.UT/TestResults/TestResults.trx        
