# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Pachoclos

on:
  push:
    branches:
      - CI-Pachoclos
      
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout
    env:
      API: ./src/AppForSEII2526.API/AppForSEII2526.API.csproj
      UT: ./test/AppForSEII2526.UT/AppForSEII2526.UT.csproj

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: |
          dotnet restore ${{ env.API }}
          dotnet restore ${{ env.UT }}

      - name: Build with dotnet
        run: |
          dotnet build ${{ env.API }}  --configuration Release --no-restore
          dotnet build ${{ env.UT }}  --configuration Release --no-restore

      - name: Run unit tests with report
        run: dotnet test ${{ env.UT }} --configuration Release --no-build --logger "trx;LogFileName=TestsResults.trx"

      - name: dotnet publish
        run: dotnet publish ${{ env.API }} -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build

    steps:
        - name: Download artifact from build job
          uses: actions/download-artifact@v4
          with:
                name: .net-app
        - name: Deploy to Azure WebApp
          id: deploy-to-webapp
          uses: azure/webapps-deploy@v3
          with:
            app-name: 'Pachoclos'
            slot-name: 'Production'
            package: .
            publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_7D6A9E6513104D7B99C1930DB296DC1A }}
            
  

    
    