# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: CD appformoviesforclassesapi

on:
  push:
    branches:
      - Copia-Marcos-CI-Pachoclos
#      - development
#    paths:
#      - 'src/AppForMovies.API**'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read #This is required for actions/checkout
    env:
      API: ./src/AppForSEII2526.API/AppForSEII2526.API.csproj
      WEB: ./src/AppForSEII2526.Web/AppForSEII2526.Web.csproj
      UT: ./test/AppForSEII2526.UT/AppForSEII2526.UT.csproj
      UIT: ./test/AppForSEII2526.UIT/AppForSEII2526.UIT.csproj

    steps:
      - name: Check out repository code branch development
        uses: actions/checkout@v4
        with:
          ref: 'Copia-Marcos-CI-Pachoclos'

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies        
        run: |  
          dotnet restore ${{ env.API }} 
          dotnet restore ${{ env.WEB }}
          dotnet restore ${{ env.UT }} 
          dotnet restore ${{ env.UIT }}

      - name: Build with dotnet
        run: |
          dotnet build ${{ env.API }} --configuration Release --no-restore
          dotnet build ${{ env.WEB }} --configuration Release --no-restore
          dotnet build ${{ env.UT }} --configuration Release --no-restore
          dotnet build ${{ env.UIT }} --configuration Release --no-restore

      - name: Run unit tests with report
        run: dotnet test ${{ env.UT }} --configuration Release --no-build --logger "trx;LogFileName=TestResults.trx"

      - name: dotnet publish
        run: dotnet publish ${{ env.API }} -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_FAAC8E81AD384B498F462AEC1E8D82D5 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_6B600146B9164A79BB651D5DE2F2CBEE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C4FA4F7EBF844AFB85277D6F9DFB59F1 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'appformoviesforclassesapi'
          slot-name: 'Production'
          package: .
